---
name: Pull Request Linting
on:
  pull_request:
    branches:
      - master
# runs github super-linter
jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '16'
      - name: Lint Code Base
        uses: github/super-linter@v5.0.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}